### ISSUE TITLE
New tool KiPadCheck

### ISSUE THREAD

**Issue by HiGregSmith** [xesscorp/kicad-3rd-party-tools#15]
Not sure how to do pull requests or work with github, but there's a new tool in development:
KiPadCheck
https://github.com/HiGregSmith/KiPadCheck

KiPadCheck provides additional basic DRC checks to KiCAD
   and lists to make tweaking pads for stencil creation easier. Functions include pad list, drill list, drill to drill spacing check, drill to track spacing check, stencil aperture check vs. stencil thicknesses, stencil aperture width vs. paste type, silk overlap of copper.

**Comment by HiGregSmith** [comment]
Most appropriate location is in
PCB Layout Tools > Layout Tools

**Comment by xesscorp** [comment]
There's a [whole page](https://github.com/xesscorp/kicad-3rd-party-tools/blob/master/contributing.md) that gives instructions on how to add your tool to the list.

**Comment by HiGregSmith** [comment]
I think I've added the pull request. GREAT INSTRUCTIONS!!

**Comment by xesscorp** [comment]
Thanks for the addition!
