### ISSUE TITLE
KiCAD Part Manager out-of-date

### ISSUE THREAD

**Issue by psheph** [xesscorp/kicad-3rd-party-tools#51]
**Describe the malfunction**
KiCad Part Manager appears not to have been updated since 2016. It uses deprecated wxPython items (as of wxPython 4). Unless someone decides to update it, it should probably be removed from the list. It also only claims compatibility with KiCAD4, but I did not get far enough to see if it will work with KiCAD5.

**To Reproduce**
1. Install packages, including setting up the mysql database
2. run `python2 -m kicadpartman.py` in the kpm directory.
3. go to Kicad menu, select "Assign Part to Schematic"
3. See deprecated item errors in terminal

**Expected behavior**
open a dialog box to select the file.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
 - KiCad version: 5.1.5-0-10-14
 - External tool name and version: kpm 0.1

**Comment by xesscorp** [comment]
I placed a warning in the description. I didn't remove it in case someone wants to use it and updates it for KiCad 5.
